require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.0'

target 'HowdjuApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'HowdjuAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.targets.each do |target|
      if target.name == "RNShareMenu"
        # I think that react-native/scripts/react_native_pods.rb is overwriting all Pod
        # IPHONEOS_DEPLOYMENT_TARGET to 11.0
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
  end
end

target 'HowdjuShareExtension' do
  use_react_native!

  # Switch between these two dependencies for local development of react-native-share-menu
  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # pod 'RNShareMenu', :path => '../../../react-native-share-menu'

  # Manually link packages here to keep your extension bundle size minimal
end
