export const editStatementPageStatementEditorId = 'editStatementPageStatementEditorId'
export const editStatementPageJustificationEditorId = 'editStatementPageJustificationEditorId'
export const statementJustificationsPageJustificationEditorId = 'statementJustificationJustificationEditorId'