export const editStatementJustificationPageEditorId = 'editStatementJustificationPageEditorId'
export const statementJustificationsPageStatementEditorId = 'statementJustificationsPageStatementEditorId'
export const statementJustificationsPageNewJustificationEditorId = 'statementJustificationsPageNewJustificationEditorId'

export const loginPageEditorId = 'loginPageEditorId'