export const editStatementJustificationPageStatementEditorId = 'editStatementJustificationPageStatementEditorId'
export const editStatementJustificationPageJustificationEditorId = 'editStatementJustificationPageJustificationEditorId'
export const statementJustificationsPageStatementEditorId = 'statementJustificationsPageStatementEditorId'
export const statementJustificationsPageJustificationEditorId = 'statementJustificationJustificationEditorId'