resource "aws_vpc" "default" {
  cidr_block                       = "172.31.0.0/16"
  assign_generated_ipv6_cidr_block = true
  tags = {
    Name      = "default-vpc"
    Terraform = "true"
  }
}

resource "aws_internet_gateway" "default" {
  vpc_id = aws_vpc.default.id
  tags = {
    Name = "default-igw"
  }
}

resource "aws_default_route_table" "default" {
  default_route_table_id = aws_vpc.default.default_route_table_id

  route {
    cidr_block = module.constants.cidr_block_ipv4_all
    gateway_id = aws_internet_gateway.default.id
  }
  route {
    ipv6_cidr_block = module.constants.cidr_block_ipv6_all
    gateway_id      = aws_internet_gateway.default.id
  }

  tags = {
    Name = "default-rtb"
  }
}


data "aws_subnet" "default_public_subnet_a" {
  id = "subnet-a1a7e2c4"
}

data "aws_subnet" "default_private_subnet_b" {
  id = "subnet-79222154"
}

data "aws_subnet" "default_public_subnet_c" {
  id = "subnet-9423d0dc"
}

data "aws_subnet" "default_public_subnet_d" {
  id = "subnet-0f7d4354"
}

data "aws_subnet" "default_public_subnet_e" {
  id = "subnet-a8eb8294"
}

data "aws_subnet" "default" {
  id = data.aws_subnet.default_private_subnet_b.id
}

data "aws_subnets" "default" {
  filter {
    name   = "vpc-id"
    values = [aws_vpc.default.id]
  }
  filter {
    name = "subnet-id"
    values = [
      # Skip subnet f because AWS only allows 5 autogenerated IPv6 CIDRs so we need to delete f.
      data.aws_subnet.default_public_subnet_a.id,
      data.aws_subnet.default_private_subnet_b.id,
      data.aws_subnet.default_public_subnet_c.id,
      data.aws_subnet.default_public_subnet_d.id,
      data.aws_subnet.default_public_subnet_e.id,
    ]
  }
}

data "aws_availability_zone" "default" {
  name = "us-east-1b"
}

resource "aws_default_network_acl" "default" {
  default_network_acl_id = aws_vpc.default.default_network_acl_id
  subnet_ids             = data.aws_subnets.default.ids

  ingress {
    rule_no    = 100
    action     = "allow"
    cidr_block = module.constants.cidr_block_ipv4_all
    protocol   = module.constants.protocol_all
    from_port  = module.constants.port_all
    to_port    = module.constants.port_all
  }
  ingress {
    rule_no         = 101
    action          = "allow"
    ipv6_cidr_block = module.constants.cidr_block_ipv6_all
    protocol        = module.constants.protocol_all
    from_port       = module.constants.port_all
    to_port         = module.constants.port_all
  }

  egress {
    rule_no    = 100
    action     = "allow"
    cidr_block = module.constants.cidr_block_ipv4_all
    protocol   = module.constants.protocol_all
    from_port  = module.constants.port_all
    to_port    = module.constants.port_all
  }
  egress {
    rule_no         = 101
    action          = "allow"
    ipv6_cidr_block = module.constants.cidr_block_ipv6_all
    protocol        = module.constants.protocol_all
    from_port       = module.constants.port_all
    to_port         = module.constants.port_all
  }

  tags = {
    Name = "default-acl"
  }
}

resource "aws_security_group" "bastion" {
  name        = "bastion-sg"
  description = "bastion host security group"
  vpc_id      = aws_vpc.default.id

  ingress {
    description      = "Allow all SSH"
    protocol         = "tcp"
    cidr_blocks      = [module.constants.cidr_block_ipv4_all]
    ipv6_cidr_blocks = [module.constants.cidr_block_ipv6_all]
    from_port        = module.constants.ssh_port
    to_port          = module.constants.ssh_port
  }

  ingress {
    description      = "Allow web for kibana"
    protocol         = "tcp"
    cidr_blocks      = [module.constants.cidr_block_ipv4_all]
    ipv6_cidr_blocks = [module.constants.cidr_block_ipv6_all]
    from_port        = module.constants.http_port
    to_port          = module.constants.http_port
  }

  egress {
    description      = "Allow all outbound"
    protocol         = module.constants.protocol_all
    cidr_blocks      = [module.constants.cidr_block_ipv4_all]
    ipv6_cidr_blocks = [module.constants.cidr_block_ipv6_all]
    from_port        = module.constants.port_all
    to_port          = module.constants.port_all
  }

  tags = {
    Name = "bastion-instance-sg"
  }
}

resource "aws_lb" "default_private" {
  name               = "default-private-lb"
  internal           = true
  load_balancer_type = "application"

  // Recommended rules: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-update-security-groups.html
  security_groups = [aws_security_group.default_private_lb.id]
  subnets         = data.aws_subnets.default.ids

  //  subnet_mapping {
  //    subnet_id = "${var.subnet_id}"
  //    allocation_id = "${module.kibana.aws_eip_id}"
  //  }

  tags = {
    Name = "default-private-lb"
  }
}

resource "aws_security_group" "default_private_lb" {
  name        = "default-private-lb-sg"
  description = "default private load balancer security group"
  vpc_id      = aws_vpc.default.id

  egress {
    cidr_blocks = [aws_vpc.default.cidr_block]
    protocol    = module.constants.protocol_all
    from_port   = module.constants.port_all
    to_port     = module.constants.port_all
  }

  tags = {
    Name = "default-private-lb-sg"
  }
}

resource "aws_default_security_group" "default" {
  vpc_id = aws_vpc.default.id

  ingress {
    self      = true
    protocol  = module.constants.protocol_all
    from_port = module.constants.port_all
    to_port   = module.constants.port_all
  }

  egress {
    cidr_blocks      = [module.constants.cidr_block_ipv4_all]
    ipv6_cidr_blocks = [module.constants.cidr_block_ipv6_all]
    protocol         = module.constants.protocol_all
    from_port        = module.constants.port_all
    to_port          = module.constants.port_all
  }

  tags = {
    Name = "default-vpc-default-sg"
  }
}

data "aws_route53_zone" "howdju" {
  name = "howdju.com."
}
