delete from actions;
delete from authentication_tokens;
delete from citations;
delete from group_permissions;
delete from groups;
delete from justification_scores;
delete from justifications;
delete from permissions;
delete from reference_urls;
delete from "references";
delete from statements;
delete from taggings;
delete from tags;
delete from tagging_scores;
delete from urls;
delete from user_groups;
delete from user_permissions;
delete from users;
delete from votes;

alter sequence statements_statement_id_seq restart with 1;
alter sequence justifications_justification_id restart with 1;
alter sequence citations_citation_id_seq restart with 1;
alter sequence references_reference_id_seq restart with 1;
alter sequence urls_url_id_seq restart with 1;
