delete from actions;
delete from authentication_tokens;
delete from citations;
delete from group_permissions;
delete from groups;
delete from justification_scores;
delete from justification_votes;
delete from justifications;
delete from permissions;
delete from reference_urls;
delete from "references";
delete from statements;
delete from taggings;
delete from tags;
delete from tagging_scores;
delete from urls;
delete from user_groups;
delete from user_permissions;
delete from users;
delete from tagging_votes;

-- alter sequence the_sequence restart;