module.exports = {
  MUST_BE_NONEMPTY: 'MUST_BE_NONEMPTY',
  INVALID_VALUE: 'INVALID_VALUE',
  IS_REQUIRED: 'IS_REQUIRED',
  IF_PRESENT_MUST_BE_ARRAY: 'IF_PRESENT_MUST_BE_ARRAY',
  INVALID_URL: 'INVALID_URL',
  STATEMENT_JUSTIFICATION_MUST_HAVE_STATEMENT_TARGET_TYPE: 'STATEMENT_JUSTIFICATION_MUST_HAVE_STATEMENT_TARGET_TYPE',
}