/** Supports our old custom validation system.  Should go away after switching all validation to JSON schemas */
export const modelErrorCodes = {
  MUST_BE_NONEMPTY: "MUST_BE_NONEMPTY",
  INVALID_VALUE: "INVALID_VALUE",
  IS_REQUIRED: "IS_REQUIRED",
  IF_PRESENT_MUST_BE_ARRAY: "IF_PRESENT_MUST_BE_ARRAY",
  IF_PRESENT_MUST_BE_NONEMPTY: "IF_PRESENT_MUST_BE_NONEMPTY",
  INVALID_URL: "INVALID_URL",
  PROPOSITION_JUSTIFICATION_MUST_HAVE_PROPOSITION_TARGET_TYPE:
    "PROPOSITION_JUSTIFICATION_MUST_HAVE_PROPOSITION_TARGET_TYPE",
  JUSTIFICATION_ROOT_PROPOSITION_ID_AND_TARGET_PROPOSITION_ID_MUST_BE_EQUAL:
    "JUSTIFICATION_ROOT_PROPOSITION_ID_AND_TARGET_PROPOSITION_ID_MUST_BE_EQUAL",
} as const;
export type ModelErrorCode =
  typeof modelErrorCodes[keyof typeof modelErrorCodes];
