const {arrayToObject} = require('../general')

const userActionsConflictCodes = arrayToObject([
  'OTHER_USERS_HAVE_ROOTED_JUSTIFICATIONS_IN_THIS_STATEMENT',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_STATEMENT',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_TEXTUAL_SOURCE_QUOTE',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_TEXTUAL_SOURCE',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_ROOTED_IN_THIS_STATEMENT',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_BASED_ON_THIS_TEXTUAL_SOURCE_QUOTE',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_BASED_ON_THIS_TEXTUAL_SOURCE',
  'OTHER_USERS_HAVE_COUNTERED_JUSTIFICATIONS_BASED_ON_THIS_TEXTUAL_SOURCE_QUOTE',
  'OTHER_USERS_HAVE_COUNTERED_JUSTIFICATIONS_BASED_ON_THIS_TEXTUAL_SOURCE',
])

module.exports = {userActionsConflictCodes}
