const {arrayToObject} = require('../general')

const userActionsConflictCodes = arrayToObject([
  'OTHER_USERS_HAVE_ROOTED_JUSTIFICATIONS_IN_THIS_PROPOSITION',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_PROPOSITION',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_WRIT_QUOTE',
  'OTHER_USERS_HAVE_BASED_JUSTIFICATIONS_ON_THIS_WRIT',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_ROOTED_IN_THIS_PROPOSITION',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_BASED_ON_THIS_WRIT_QUOTE',
  'OTHER_USERS_HAVE_VOTED_ON_JUSTIFICATIONS_BASED_ON_THIS_WRIT',
  'OTHER_USERS_HAVE_COUNTERED_JUSTIFICATIONS_BASED_ON_THIS_WRIT_QUOTE',
  'OTHER_USERS_HAVE_COUNTERED_JUSTIFICATIONS_BASED_ON_THIS_WRIT',
])

module.exports = {userActionsConflictCodes}
