variable "aws_account_id" {}
variable "aws_region" {}
variable "ecs_cluster_id" {}
variable "task_desired_count" {}
variable "repository_name" {}
variable "container_version" {}
variable "task_cpu" {}
variable "task_memory_mib" {}
variable "log_group" {}
variable "vpc_id" {}
variable "lb_arn" {}
variable "lb_security_group_id" {}
variable "elasticsearch_ingress_cidr" {}
variable "lb_port" {}
