module.exports = {
  CREATE_USERS: 'CREATE_USERS',
  DELETE_JUSTIFICATIONS: 'DELETE_JUSTIFICATIONS',
  UPDATE_STATEMENTS: 'UPDATE_STATEMENTS',
  DELETE_STATEMENTS: 'DELETE_STATEMENTS',
  UPDATE_CITATION_REFERENCES: 'UPDATE_CITATION_REFERENCES',
}