# https://www.elastic.co/guide/en/kibana/current/settings.html

server.name: kibana
server.host: "0.0.0.0"
elasticsearch.url: "${ELASTICSEARCH_URL}"
xpack.monitoring.ui.container.elasticsearch.enabled: true
