name: CI

on:
  push:
    branches: [
      "master",
      "feature/*",
    ]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  premerge-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Corepack
        # Enables yarn v2
        run: corepack enable
      - name: Yarn install
        run: yarn install
      - name: Lint
        run: yarn run lint:all
      - name: Typecheck
        run: yarn run typecheck:all
      - name: Test
        run: yarn run test:all --ci
      - name: Custom checks
        run: yarn run custom-check:all
