name: Deploy to preprod

concurrency: preprod

on:
  push:
    branches:
      # Treat master as a CD branch for preprod.
      - master
  workflow_dispatch:

env:
  AWS_REGION: us-east-1 

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: preprod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Corepack
        # Enables yarn v2
        run: corepack enable
      - name: Yarn install
        run: yarn install
      - name: Deploy API
        run: yarn run deploy:api -- pre-prod
      - name: Deploy UI
        run: yarn run deploy:ui:pre-prod
